version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.3
  - dependency-name: cryptography
    versions:
    - 3.3.1
    - 3.4.1
    - 3.4.3
    - 3.4.4
    - 3.4.5
  - dependency-name: flake8
    versions:
    - 3.8.4
