# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-noggin-messages.spec

# add or remove files that should be synced
files_to_sync:
    - python-noggin-messages.spec
    - 0001-Revert-Include-additional-files-in-the-sdist.patch
    - README.md
    - sources
    - .packit.yaml


# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: noggin-messages
# downstream (Fedora) RPM package name
downstream_package_name: python-noggin-messages
upstream_tag_template: v{version}

srpm_build_deps:
    - wget

actions:
  create-archive:
    - "/builddir/.local/bin/poetry build -f sdist"
    - "sh -c 'echo dist/noggin_messages-$(/builddir/.local/bin/poetry version -s).tar.gz'"
  get-current-version:
    - "/builddir/.local/bin/poetry version -s"
  post-upstream-clone:
    # fetch specfile, patches, documentation etc. from the downstream
    - "wget https://src.fedoraproject.org/rpms/python-noggin-messages/raw/main/f/python-noggin-messages.spec -O python-noggin-messages.spec"
    - "wget https://src.fedoraproject.org/rpms/python-noggin-messages/raw/main/f/0001-Revert-Include-additional-files-in-the-sdist.patch -O 0001-Revert-Include-additional-files-in-the-sdist.patch"
    - "wget https://src.fedoraproject.org/rpms/python-noggin-messages/raw/main/f/README.md -O README.md"
    - "wget https://src.fedoraproject.org/rpms/python-noggin-messages/raw/main/f/sources -O sources"
    - "sh -c 'curl -sSL https://install.python-poetry.org | python3 -'"

jobs:
  # upon upstream PRs, perform COPR builds
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon upstream PRs, test builds
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon upstream releases, perform COPR builds
  - job: copr_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon upstream releases, test builds
  - job: tests
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon downstream changes, create a PR upstream with sync'd files from above
  - job: sync_from_downstream
    trigger: commit

  # land upstream release in fedora dist-git - no builds
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create an srpm from upstream and submit a scratch build to koji
  - job: production_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # downstream automation

  # trigger a build in koji for a new dist-git commit
  - job: koji_build
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create a new update in bodhi for a successful koji build. directly related to `koji_build`
  - job: bodhi_update
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development
