name: Approve Dependabot PRs
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      pr-number:
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    name: Approve minor and patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          approve-only: true
          pr-number: ${{ github.event.inputs.pr-number }}
