on: [push, pull_request]

name: Tests

jobs:
  misc_tests:
    name: Misc tests
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf install -y pre-commit git krb5-devel openldap-devel
          pip install poetry>=1.2
      - name: Mark the working directory as safe for Git
        run: git config --global --add safe.directory $PWD
      - name: Run tests
        run: tox -e ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env:
          - lint
          - format
          - licenses
          - security
          - docs

  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf install -y pre-commit git krb5-devel openldap-devel
          pip install poetry>=1.2
      - name: Mark the working directory as safe for Git
        run: git config --global --add safe.directory $PWD
      - name: Run tests
        run: tox -e ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env:
          - py38
          - py39
          - py310
          - py311
